infor = {
    'curve_injec': False, 
    'curve_type': None,
    'cut_times': None,
    'cut_trans': None,
    'cut_numbe': None,
    'cut_start_index': None,
    'detre_time_scale': None,
    'detre_type': None,
    'eb': None,
    'file_name': None,
    'injec_times': None,
    'inter_type': None,
    'initi_paddi': None,
    'linea_limb_darke_coeff': None,
    'max_ampli': None,
    'model_file': None,
    'moon_densi': None,
    'moon_eccen': None,
    'moon_epoch': None,
    'moon_incli': None,
    'moon_mass': None,
    'moon_numbe': None,
    'moon_perio': None,
    'moon_radiu': None,
    'moon_sin_w': None,
    'moon_signa': None,
    'moon_signa_time': None,
    'plane_cut_injec': None,
    'plane_densi': None,
    'plane_eccen': None,
    'plane_epoch': None,
    'plane_incli': None,
    'plane_mass': None,
    'plane_moon_cut_injec': None,
    'plane_numbe': None,
    'plane_perio': None,
    'plane_radiu': None,
    'plane_sin_w': None,
    'plane_signa': None,
    'plane_signa_time': None,
    'plane_trans_durat': None,
    'plane_type': None,
    'predi': None,
    'quadr_limb_darke_coeff': None,
    'ratio_moon_plane_radiu': None,
    'ratio_moon_stell_radiu': None,
    'ratio_plane_stell_radiu': None,
    'raw_curve_lengt': None,
    'rms': None,
    'signa': None,
    'snr': None,
    'stell_effec_tempe': None,
    'stell_magni': None,
    'stell_mass': None,
    'stell_radiu': None,
    'tic_id': None,
    'toi': None,
    'trape_trans': None,
    'type_calcu': None,
    'type_limb_darke': None,
    'type_orbit_archi': None,
    'unmod_plane_moon_cut_injec': None
}

forma_names = {
    'curve_injec': 'Curve Injected',
    'curve_type': 'Curve Type',
    'cut_times': 'Cut Times',
    'cut_trans': 'Cut Transit', 
    'cut_numbe': 'Cut Number',
    'cut_start_index': 'Cut Start Index',
    'detre_time_scale': 'Detrended Time Scale [days]',
    'detre_type': 'Detrended Type',
    'eb': 'Eclipsing Binary',
    'file_name': 'File Name',
    'injec_times': 'Injection Times',
    'inter_type': 'Interpolation Spline',
    'initi_paddi': 'Initial Padding',
    'linea_limb_darke_coeff': 'Linear Limb Darkening Coefficient',
    'max_ampli': 'Max Amplitude',
    'model_file': 'Model File',
    'moon_densi': 'Moon Density [g/cm^3]',
    'moon_eccen': 'Moon Eccentricity',
    'moon_epoch': 'Moon Epoch [BJD]',
    'moon_incli': 'Moon Inclination [°]',
    'moon_mass': 'Moon Mass [M⨂]',
    'moon_numbe': 'Number of Moons',
    'moon_perio': 'Moon Period [days]',
    'moon_radiu': 'Moon Radius [R⨂]',
    'moon_sin_w': 'Planet Sin Argument of Periapsis [AU]',
    'moon_signa': 'Moon Signal',
    'moon_signa_time': 'Moon Signal Time',
    'plane_cut_injec': 'Cut Injected (Planet)',
    'plane_densi': 'Planet Density [g/cm^3]',
    'plane_eccen': 'Planet Eccentricity',
    'plane_epoch': 'Planet Epoch [BJD]',
    'plane_incli': 'Planet Inclination [°]',
    'plane_mass': 'Planet Mass [M⨂]',
    'plane_moon_cut_injec': 'Cut Injected (Planet, Moon)',
    'plane_numbe': 'Number of Planets',
    'plane_perio': 'Planet Period [days]',
    'plane_radiu': 'Planet Radius [R⨂]',
    'plane_sin_w': 'Planet Sin Argument of Periapsis [AU]',
    'plane_signa': 'Planet Signal',
    'plane_signa_time': 'Planet Signal Time',
    'plane_trans_durat': 'Planet Transit Duration [days]',
    'plane_type': 'Planet Type',
    'predi': 'Prediction',
    'quadr_limb_darke_coeff': 'Quadratic Limb Darkening Coefficient',
    'ratio_moon_plane_radiu': 'Ratio of Moon to Planetary Radius',
    'ratio_moon_stell_radiu': 'Ratio of Moon to Stellar Radius', 
    'ratio_plane_stell_radiu': 'Ratio of Planetary to Stellar Radius',
    'raw_curve_lengt': 'Length of Initial Light Curve',
    'rms': 'Root Mean Square',
    'signa': 'Signal',
    'snr': 'Signal to Noise Ratio',
    'stell_effec_tempe': 'Stellar Effective Temperature [C°]',
    'stell_magni': 'Stellar Magnitude',
    'stell_mass': 'Stellar Mass [M☉]',
    'stell_radiu': 'Stellar Radius [R☉]',
    'tic_id': 'TIC ID',
    'toi': 'TOI',
    'trape_trans': 'Trapezoidal Transits',
    'type_calcu': 'Type Calculation',
    'type_limb_darke': 'Type of Limb Darkening',
    'type_orbit_archi': 'Type of Orbital Architecture',
    'unmod_plane_moon_cut_injec': 'Unmodified Cut Injected (Planet, Moon)'
}


main_path = '/home/rfradkin/xom/'
raw_tess_path = '/scratch/data/tess/lcur/spoc/raws/'
tess_metad_path = '/data/scratch/data/tess/meta/'
xom_data_path = '/data/scratch/data/moon/'
