forma_names = {
    'curve_injec': 'Curve Injected',
    'curve_type': 'Curve Type',
    'cut_times': 'Cut Times',
    'cut_trans': 'Cut Transit', 
    'cut_numbe': 'Cut Number',
    'cut_start_index': 'Cut Start Index',
    'detre_time_scale': 'Detrended Time Scale [days]',
    'detre_type': 'Detrended Type',
    'eb': 'Eclipsing Binary',
    'file_name': 'File Name',
    'injec_times': 'Injection Times',
    'inter_type': 'Interpolation Spline',
    'initi_paddi': 'Initial Padding',
    'linea_limb_darke_coeff': 'Linear Limb Darkening Coefficient',
    'max_ampli': 'Max Amplitude',
    'model_file': 'Model File',
    'moon_densi': 'Moon Density [g/cm^3]',
    'moon_eccen': 'Moon Eccentricity',
    'moon_epoch': 'Moon Epoch [BJD]',
    'moon_incli': 'Moon Inclination [°]',
    'moon_mass': 'Moon Mass [M⨂]',
    'moon_numbe': 'Number of Moons',
    'moon_perio': 'Moon Period [days]',
    'moon_radiu': 'Moon Radius [R⨂]',
    'moon_sin_w': 'Planet Sin Argument of Periapsis [AU]',
    'moon_signa': 'Moon Signal',
    'plane_cut_injec': 'Cut Injected (Planet)',
    'plane_densi': 'Planet Density [g/cm^3]',
    'plane_eccen': 'Planet Eccentricity',
    'plane_epoch': 'Planet Epoch [BJD]',
    'plane_incli': 'Planet Inclination [°]',
    'plane_mass': 'Planet Mass [M⨂]',
    'plane_moon_cut_injec': 'Cut Injected (Planet, Moon)',
    'plane_numbe': 'Number of Planets',
    'plane_perio': 'Planet Period [days]',
    'plane_radiu': 'Planet Radius [R⨂]',
    'plane_sin_w': 'Planet Sin Argument of Periapsis [AU]',
    'plane_signa': 'Planet Signal',
    'plane_type': 'Planet Type',
    'predi': 'Prediction',
    'quadr_limb_darke_coeff': 'Quadratic Limb Darkening Coefficient',
    'ratio_moon_plane_radiu': 'Ratio of Moon to Planetary Radius',
    'ratio_moon_stell_radiu': 'Ratio of Moon to Stellar Radius', 
    'ratio_plane_stell_radiu': 'Ratio of Planetary to Stellar Radius',
    'signa': 'Signal',
    'stell_effec_tempe': 'Stellar Effective Temperature [C°]',
    'stell_magni': 'Stellar Magnitude',
    'stell_mass': 'Stellar Mass [M☉]',
    'stell_radiu': 'Stellar Radius [R☉]',
    'tic_id': 'TIC ID',
    'toi': 'TOI',
    'trape_trans': 'Trapezoidal Transits',
    'type_calcu': 'Type Calculation',
    'type_limb_darke': 'Type of Limb Darkening',
    'type_orbit_archi': 'Type of Orbital Architecture'
}
